name: Docker Image CI

on:
  push:
    branches:
      - !master
    paths:
      - !charts

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cert-manager-webhook-ovh:$(date +%s)